---
title: "JSS"
author: "Jonathan Rosenblatt"
date: "May 29, 2016"
output: html_document
---

```{r preliminaries}
library(magrittr)
library(chords)
```


# Brazil Data Analysis

## MLE
```{r}
# Import data in RDS file format:
data(brazil)
head(brazil)

# Initialize RDS object:
rds.object<- initializeRdsObject(brazil)

# MLE Estimate:
rds.object <- Estimate.b.k(rds.object = rds.object )

# Get estimates:
estimate.1 <- rds.object$estimates$Nk.estimates
plot(estimate.1, type='h')
table(estimate.1)

# How many degrees were imputed?:
table(rds.object$estimates$convergence)

# Recover theta assuming b.k=b_0*k^theta
getTheta(rds.object)
```

## Delete-d 
```{r}
jack.control <- makeJackControl(3, 1e2)
rds.object.2 <- Estimate.b.k(rds.object, type='leave-d-out', jack.control = jack.control)

estimate.2 <- rds.object.2$estimates$Nk.estimates
table(estimate.2)
sum(estimate.2)
```

## Parametric smoothing
```{r}
rds.object.3 <- Estimate.b.k(rds.object, type='parametric')

estimate.3 <- rds.object.3$estimates$Nk.estimates
plot(estimate.3, type='h')
table(estimate.3)
sum(estimate.3[estimate.3<Inf])
```

## Integrated MLE
```{r}
rds.object.4 <- Estimate.b.k(rds.object, type='integrated')

estimate.4 <- rds.object.4$estimates$Nk.estimates
plot(estimate.4, type='h')
table(estimate.4)
sum(estimate.4)
```


## Heuristic scaling
```{r}
rds.object.5 <- Estimate.b.k(rds.object, type='rescaling')

estimate.5 <- rds.object.5$estimates$Nk.estimates
plot(estimate.5, type='h')
table(estimate.5)
sum(estimate.5)
```


## Jeffrey's Prior
```{r}
rds.object.6 <- Estimate.b.k(rds.object, type='jeffreys')

estimate.6 <- rds.object.6$estimates$Nk.estimates
plot(estimate.6, type='h')
table(estimate.6)
sum(estimate.6)
```



# Simulated Data Analysis


## Simulate data
```{r make data}
dk <- c(2, 5, 10, 20) # unique degree classes
true.dks <- rep(0,max(dk))
true.dks[dk] <- dk
true.Nks <- rep(0,max(dk))
true.Nks[dk] <- 1e3
beta <- 1e #5e-6
theta <-  0.1
true.log.bks <- rep(-Inf, max(dk))
true.log.bks[dk] <- theta*log(beta*dk)
sample.length <- 1e3
nsims <- 1e1

simlist <- list()
for(i in 1:nsims){
  simlist[[i]] <- makeRdsSample(
    N.k =true.Nks , 
    b.k = exp(true.log.bks),
    sample.length = sample.length)
}
```


## MLE
```{r}
nvec.1 <- rep(NA, nsims)
converged.1<- rep(NA, nsims)
simlist.1 <- NULL
for(i in 1:nsims){
  simlist.1[[i]] <- Estimate.b.k(rds.object = simlist[[i]])
  nvec.1[i] <- sum(simlist.1[[i]]$estimates$Nk.estimates)
  converged.1[i] <- sum(simlist.1[[i]]$estimates$convergence, na.rm=TRUE)
}

hist(nvec.1)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.1, na.rm = TRUE), lty=2) # Median of estimated population size
```


## Parametric smoothing
```{r}
nvec.3 <- rep(NA, nsims)
converged.3<- rep(NA, nsims)
simlist.3 <- NULL
for(i in 1:nsims){
  try({
  simlist.3[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='parametric')
  nvec.3[i] <- sum(simlist.3[[i]]$estimates$Nk.estimates)
  converged.3[i] <- sum(simlist.3[[i]]$estimates$convergence, na.rm=TRUE)      
  })
}

hist(nvec.3)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.3, na.rm = TRUE), lty=2) # Median of estimated population size
```


## Integrated MLE
```{r}
nvec.4 <- rep(NA, nsims)
converged.4<- rep(NA, nsims)
simlist.4 <- NULL
for(i in 1:nsims){
  try({
  simlist.4[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='integrated')
  nvec.4[i] <- sum(simlist.4[[i]]$estimates$Nk.estimates)
  converged.4[i] <- sum(simlist.4[[i]]$estimates$convergence, na.rm=TRUE)      
  })
}

hist(nvec.4)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.4, na.rm = TRUE), lty=2) # Median of estimated population size
```


## Heuristic scaling
```{r}
nvec.5 <- rep(NA, nsims)
converged.5<- rep(NA, nsims)
simlist.5 <- NULL
for(i in 1:nsims){
  try({
  simlist.5[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='rescaling')
  nvec.5[i] <- sum(simlist.5[[i]]$estimates$Nk.estimates)
  converged.5[i] <- sum(simlist.5[[i]]$estimates$convergence, na.rm=TRUE)      
  })
}

hist(nvec.5)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.5, na.rm = TRUE), lty=2) # Median of estimated population size
```


## Jeffrey's Prior
```{r}
nvec.6 <- rep(NA, nsims)
converged.6<- rep(NA, nsims)
simlist.6 <- NULL
for(i in 1:nsims){
  try({
  simlist.6[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='jeffreys')
  nvec.6[i] <- sum(simlist.6[[i]]$estimates$Nk.estimates)
  converged.6[i] <- sum(simlist.6[[i]]$estimates$convergence, na.rm=TRUE)      
  })
}

hist(nvec.6)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.6, na.rm = TRUE), lty=2) # Median of estimated population size
```


## Observed
```{r}
nvec.7 <- rep(NA, nsims)
converged.7<- rep(NA, nsims)
simlist.7 <- NULL
for(i in 1:nsims){
  try({
  simlist.7[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='observed')
  nvec.7[i] <- sum(simlist.7[[i]]$estimates$Nk.estimates)
  converged.7[i] <- sum(simlist.7[[i]]$estimates$convergence, na.rm=TRUE)      
  })
}

hist(nvec.7)
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.7, na.rm = TRUE), lty=2, lwd=2) # Median of estimated population size
```


## Delete-d 
```{r}
jack.control <- makeJackControl(d = 5e1, B = 2e2)

nvec.2 <- rep(NA, nsims)
converged.2<- rep(NA, nsims)
simlist.2 <- NULL
for(i in 1:nsims){
  simlist.2[[i]] <- Estimate.b.k(rds.object = simlist.1[[i]], type='leave-d-out', jack.control)
  nvec.2[i] <- sum(simlist.1[[i]]$estimates$Nk.estimates)
  converged.2[i] <- sum(simlist.1[[i]]$estimates$convergence, na.rm=TRUE)
}

hist(nvec.2, xlim=c(5e2,4e3))
abline(v=sum(true.Nks), col='red') # True population size
abline(v=median(nvec.2, na.rm = TRUE), lty=2) # delete-d median
abline(v=median(nvec.1, na.rm = TRUE), lty=3) # MLE median
```
